name: Publish to GH Pages

#on:
#  push:
#    branches: [master]

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses action/checkout@v2
    - uses: action/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        sudo apt-get install python3-pip
        pip install git+git://github.com/executablebookproject/cli.git#egg=master
        pip install ghp-import
        PATH="${PATH}:${HOME}/.local/bin"
    - run: |
        jupyter-book toc .
    - run: |
        jupyter-book build .

    - run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" 
        
        ghp-import _build/html -f -p -n
